export const initialCoursesState = {
    title: {
        value: '',
        errors: {},
        isTouched: false,
        isValid: false,
        type: 'text',
        controlName: 'title',
        classNameGroup: 'input-group mb-3',
        spanGroup: 'Название курса'
    },
    subtitle: {
        value: '',
        errors: {},
        isTouched: false,
        isValid: false,
        type: 'text',
        controlName: 'subtitle',
        classNameGroup: 'input-group mb-3',
        spanGroup: 'Подзаголовок'
    },
    price: {
        value: '',
        errors: {},
        isTouched: false,
        isValid: false,
        type: 'text',
        controlName: 'price',
        classNameGroup: 'input-group mb-3',
        spanGroup: 'Стоимость',
        spanGroup2: 'руб.',
    },
    duration: {
        value: '',
        errors: {},
        isTouched: false,
        isValid: false,
        type: 'text',
        controlName: 'duration',
        classNameGroup: 'input-group mb-3',
        spanGroup: 'Продолжительность',
    },
    ageGroup: {
        value: '',
        errors: {},
        isTouched: false,
        isValid: false,
        type: 'text',
        controlName: 'ageGroup',
        classNameGroup: 'input-group mb-3',
        label: 'Возрастная категория',
    },
    durationGroup: {
        value: '',
        errors: {},
        isTouched: false,
        isValid: false,
        type: 'text',
        controlName: 'durationGroup',
        classNameGroup: 'input-group mb-3',
        label: 'Продолжительность курса',
    },
    description: {
        value: '',
        errors: {},
        isTouched: false,
        isValid: false,
        type: 'text',
        controlName: 'description',
        classNameGroup: 'mb-3',
        label: 'Краткое описание курса',
        textAreaId: 'textarea1'
    },
    content: {
        value: '',
        errors: {},
        isTouched: false,
        isValid: false,
        type: 'text',
        controlName: 'description',
        classNameGroup: 'mb-3',
        label: 'Содержание курса',
        textAreaId: 'textarea2'
    },
    video: {
        value: '',
        errors: {},
        isTouched: false,
        isValid: false,
        type: 'file',
        controlName: 'duration',
        classNameGroup: 'input-group mb-3',
        spanGroup: 'Видео',
        textAreaId: 'videoFile'
    },
    fotos: {
        value: '',
        errors: {},
        isTouched: false,
        isValid: false,
        type: 'file',
        controlName: 'fotos',
        classNameGroup: 'input-group mb-3',
        spanGroup: 'Фото для слайдера',
        textAreaId: 'videoFile',
        multiple: 'multiple'
    },
}